apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec: 
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database
        image: mysql:5.6
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: database.password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: database.username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: database.password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysqlsecret
                key: database.name  
        volumeMounts:
          -  name: database
             mountPath: /var/lib/mysql
      volumes:
        -  name: database
           persistentVolumeClaim: 
             claimName: database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels: 
    volume: mysqlvolume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv0002/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests: 
      storage: 1Gi
  selector:
    matchLabels:
      volume: mysqlvolume